name: Pull request or push to Dev Branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Deploy website and sentry
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
      HEROKU_APP_NAME: 'dalenguyen-me'
      NODE_OPTIONS: '--max_old_space_size=4096'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: node_modules cache
        uses: actions/cache@v3
        id: node_modules-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: pnpm cache
        if: steps.node_modules-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        id: pnpm-store
        with:
          path: ~/.pnpm-store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: npx nx deploy portfolio

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: main
          FOLDER: docs
