name: Pull request or push to Dev Branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Deploy website and sentry
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
      HEROKU_APP_NAME: 'dalenguyen-me'
      NODE_OPTIONS: '--max_old_space_size=4096'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ng-easy/npm-setup@v1.7.2

      - name: NPM install
        uses: bahmutov/npm-install@v1.6.0

      - name: Build
        run: npm run build

      - name: Deploy
        uses: actions/deploy-pages@v1.2.4
        with:
          token: ${{ secrets.GH_TOKEN }}
